# Site settings
title: Gabriel Cardoso
description: 'Software Development Student'
url: 'http://gabriel-card.github.io/''
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Gabriel Cardoso'
  email: gbl.oxen@hotmail.com
  twitter_username: none
  facebook_username: gabrielcardosant
  github_username:  gabriel-card
  linkedin_username:  gabriel-cardoso

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
